### PR TITLE
feat: snap package

### PR DESCRIPTION
**Pull request by francisdb**
Work in progress

~~The fact that most repos require latest cmake is causing some issues~~

To test this 

Make sure you have the required tools
https://snapcraft.io/docs/create-a-new-snap#heading--setup

```
snapcraft
sudo snap install ./vpinball_10.8.1-git_amd64.snap --dangerous --devmode
```

### CODE REVIEW

**Comment by francisdb** [comment]
Totally confused by this stuff

```
➜  ~ vpinball -listres
2024-01-19 16:26:39.588 INFO  [550349] [VPApp::InitInstance@837] Starting VPX - v10.8.1 Beta (Rev. 0 (unknown), linux OpenGL 64bits)
2024-01-19 16:26:39.588 INFO  [550349] [VPApp::InitInstance@840] Settings file was loaded from /home/xyz/snap/vpinball/x7/.vpinball/VPinballX.ini
2024-01-19 16:26:39.588 INFO  [550349] [VPApp::InitInstance@841] m_logicalNumberOfProcessors=24
2024-01-19 16:26:39.588 INFO  [550349] [VPApp::InitInstance@842] m_szMyPath=/snap/vpinball/x7/usr/local/
2024-01-19 16:26:39.588 INFO  [550349] [VPApp::InitInstance@843] m_szMyPrefPath=/home/xyz/snap/vpinball/x7/.vpinball/
2024-01-19 16:26:39.588 INFO  [550349] [VPApp::InitInstance@849] Available fullscreen resolutions:
2024-01-19 16:26:39.588 INFO  [550349] [VPApp::InitInstance@856] display 0: 0x0 (depth=0, refreshRate=0)
```

* different home directory which seems to change per revision
* no displays found

**Comment by jsm174** [comment]
I don't really know anything about snap, but I did read it's goal is to built the app from source. 

If `-listres` returns nothing, I think it's compiling SDL without a dependency. I know you've been experimenting with Wayland and I have no clue on that, but for X11, I know you need `xrandr`.

If you look at the github ci code, you'll see the deps we install:

`sudo apt install cmake bison zlib1g-dev libdrm-dev libgbm-dev libglu1-mesa-dev libegl-dev libudev-dev libx11-dev libxrandr-dev`

**Comment by francisdb** [comment]
Stuck on Alsa, setting that up in snaps is a pain
Alsa is required by BASS
Any proper app these days uses pipewire or pulseaudio.
Dropping this for now until #759 is tackled.

```
ALSA lib control.c:1529:(snd_ctl_open_noupdate) Invalid CTL hw:0
ALSA lib control.c:1529:(snd_ctl_open_noupdate) Invalid CTL hw:1
ALSA lib control.c:1529:(snd_ctl_open_noupdate) Invalid CTL hw:2
ALSA lib control.c:1529:(snd_ctl_open_noupdate) Invalid CTL hw:3
ALSA lib control.c:1529:(snd_ctl_open_noupdate) Invalid CTL hw:0
[1]    1058997 segmentation fault (core dumped)  vpinball -play 
```

**Comment by jsm174** [comment]
is it okay to close this? We can open it back up if you resume work on it?

**Pull request closed without merging**
