### PR TITLE
fix(standalone): pup refactor gone wrong

### PR DESCRIPTION
**Pull request by francisdb**
Found in Batman 66 script

ref https://github.com/jsm174/vpx-standalone-scripts/issues/284

### CODE REVIEW

**Comment by francisdb** [comment]
```vbscript
Set PuPlayer = CreateObject("PinUpPlayer.PinDisplay")  
```

**Comment by jsm174** [comment]
@francisdb actually, this is probably a bug when I did a mass rename from PinUpPlayer to PUP. Can you get rid of that first case and I can merge it.

**Comment by francisdb** [comment]
@jsm174 done

**Comment by jsm174** [comment]
> @jsm174 done

Thanks!

**Pull request merged**
