### PR TITLE
blind shot at fixing RotateSurface, as the current implementation sho…

### PR DESCRIPTION
**Pull request by toxieainc**
…uld lead to holes if angle is not a multiple of 90 (maybe 45 works, too)

### CODE REVIEW

**Comment by toxieainc** [comment]
As i don't have the time at the moment to build standalone on Linux, etc, (and my windows standalone build efforts are still unfinished), please review and test if the code works as intended.
I just stumbled over this while reviewing the B2S code.

**Comment by jsm174** [comment]
Wow. super excited to try this. Just went to compile:

```
forms/FormBackglass.cpp
[build] /Users/jmillard/jason/vpinball/standalone/inc/b2s/forms/FormBackglass.cpp:520:48: error: invalid operands to binary expression ('const char *' and 'const char *')
[build]                       (rominverted ? "I" : "") + (romidtype == eRomIDType_Lamp ? "L" : romidtype == eRomIDType_Solenoid ? "S" : "GI") + 
[build]                       ~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] /Users/jmillard/jason/vpinball/standalone/inc/b2s/forms/FormBackglass.cpp:1365:14: error: use of undeclared identifier 'rotatingangle'; did you mean 'rotatingAngle'?
[build]       while (rotatingangle < 360) {
[build]              ^~~~~~~~~~~~~
[build]              rotatingAngle
[build] /Users/jmillard/jason/vpinball/standalone/inc/b2s/forms/FormBackglass.cpp:1363:11: note: 'rotatingAngle' declared here
[build]       int rotatingAngle = 0;
[build]           ^
[build] 2 errors generated.
```

**Comment by jsm174** [comment]
So I thought this was related to https://github.com/vpinball/vpinball/issues/1286, however I don't believe it is.

I did try it out with ss, and now the rotation is broken:


https://github.com/vpinball/vpinball/assets/1197137/6bdc6fab-cdf9-4be4-adcb-0875020b8254

**Comment by toxieainc** [comment]
Ah, seems like i screwed up some of the offsets (translation), but the rotation itself seems to be fine?

The basic idea of the tweak is just to iterate over destination instead of source, in order to fill up all pixels.
Otherwise, the other way round, some pixels may be missed (=black spots).

**Comment by toxieainc** [comment]
@jsm174 Could you please try again? Thanks!

**Comment by jsm174** [comment]
works great! Hopefully me merging was okay.  Tested SS and Bad Cats as they use this feature!

**Comment by toxieainc** [comment]
Yup, absolutely, thanks for testing/merging!

**Pull request merged**
