### PR TITLE
Initial Pup Pack Support for standalone

### PR DESCRIPTION
**Pull request by YellowLabrador**
Resubmitting it for 10.8.1 as requested. I also removed the ffmpeg based video player.

I built it and tried it on macos-arm64 only.

### CODE REVIEW

**Comment by YellowLabrador** [comment]
@jsm174 FYI

**Comment by francisdb** [comment]
```
2024-01-26 10:45:47.171 INFO  [355342] [PinUpPlayerPinDisplay::B2SInit@230] Playlists loaded: file=/Users/francisdb/vpinball/tables/Total Nuclear Annihilation (Spooky 2017)/tna/playlists.pup, size=19
2024-01-26 10:45:47.172 INFO  [355342] [PinUpPlayerPinDisplay::B2SInit@251] Triggers loaded: file=/Users/francisdb/vpinball/tables/Total Nuclear Annihilation (Spooky 2017)/tna/triggers.pup, size=50
2024-01-26 10:45:47.173 INFO  [355342] [PinUpPlayerPinDisplay::B2SInit@272] Screens loaded: file=/Users/francisdb/vpinball/tables/Total Nuclear Annihilation (Spooky 2017)/tna/screens.pup, size=2
2
```

Does this mean the pup is being loaded?
I see no extra windows?

**Comment by francisdb** [comment]
I really want to test this stuff! Mind sharing what version of The Munsters you are using and if the vbs file needs patching the patched file?

**Comment by jsm174** [comment]
> ```
> 2024-01-26 10:45:47.171 INFO  [355342] [PinUpPlayerPinDisplay::B2SInit@230] Playlists loaded: file=/Users/francisdb/vpinball/tables/Total Nuclear Annihilation (Spooky 2017)/tna/playlists.pup, size=19
> 2024-01-26 10:45:47.172 INFO  [355342] [PinUpPlayerPinDisplay::B2SInit@251] Triggers loaded: file=/Users/francisdb/vpinball/tables/Total Nuclear Annihilation (Spooky 2017)/tna/triggers.pup, size=50
> 2024-01-26 10:45:47.173 INFO  [355342] [PinUpPlayerPinDisplay::B2SInit@272] Screens loaded: file=/Users/francisdb/vpinball/tables/Total Nuclear Annihilation (Spooky 2017)/tna/screens.pup, size=2
> 2
> ```
> 
> Does this mean the pup is being loaded? I see no extra windows?
> 
> This is `VPW Total Nuclear Annihilation`

These specific messages have been in standalone for a year now. I had written code to parse the csv files, but that was as far as I got. 

I didn't forget about this, I promise I will get back to it.

**Comment by YellowLabrador** [comment]
@francisdb I uploaded the patched VBS for Munsters here - https://github.com/YellowLabrador/vpx-standalone-scripts/tree/master/Munsters%20(Original%202020)%201.05

I run it with this command: `./VPinballX_GL -DisableTrueFullscreen -play <path>/Munsters\ \(Original\ 2020\)\ 1.05.vpx` 

You need to have both PinMAMEWindow and B2S configured. The current Pup logic looks for them to instantiate the Windows. My thought in reusing the configuration was for users not to have to create another block with the same information.

This is what I have in my VPinballX.ini:

```
PinMAMEWindow = 1
PinMAMEWindowX = 0
PinMAMEWindowY = 0
PinMAMEWindowWidth = 640
PinMAMEWindowHeight = 360
```
and

```
B2S = 1
B2SHideGrill =
B2SHideB2SDMD =
B2SHideDMD =
B2SDualMode =
B2SBackglassX = 0
B2SBackglassY = 0
B2SBackglassWidth = 640
B2SBackglassHeight = 360
```

**Comment by francisdb** [comment]
thanks @YellowLabrador 

Got it running on MacOS. Got some output for "Total Nuclear Annihilation" as well. Darkest Dungeon crashes. Will try Linux later today.

So how do you see this evolving?

**Comment by jsm174** [comment]
> So how do you see this evolving?

Patience.

**Comment by jsm174** [comment]
superseded by https://github.com/vpinball/vpinball/pull/1690

**Pull request closed without merging**
