### PR TITLE
feat: window icon

### PR DESCRIPTION
**Pull request by francisdb**
see https://github.com/jsm174/vpx-standalone-scripts/issues/95

_This is my first c++ code so be kind ;-)_

This is what you used to get

image

With this applied

image

### CODE REVIEW

**Comment by francisdb** [comment]
Proper Linux desktop integration like we have for MacOS now can be added next.

**Comment by jsm174** [comment]
Very cool. I will check this out tonight to make sure we are all good on the iOS / android side before merging.

**Comment by francisdb** [comment]
Should CI not be validating my PR?

**Comment by francisdb** [comment]
Still need to check on linux if the png instead of ico works

**Comment by francisdb** [comment]
Confirmed working

**Comment by francisdb** [comment]
Seems to no longer do it's thing in Ubuntu 24.04 (Wayland)

**Pull request merged**
