### PR TITLE
Improve script error handling

### PR DESCRIPTION
**Pull request by CraftedCart**
This pull request tries to improve script error messages.

New error dialog and log

When a script debugger is installed, runtime errors now contain a stack trace, as well as the values of local variables/function arguments at each point in the stack. On the new runtime error dialog, you can also now choose to suppress future error dialogs (for the play session), or stop running the table altogether, which should help in the case that something is throwing an error on a repeating timer.

As for what counts as a script debugger, thaaat's been hard to find info on. From my mucking around, having Visual Studio 2010 Isolated Shell works to give more detailed errors. If no debugger is found, the usual simple error information is shown (see image below).

In addition, there's a new error log at the bottom of the script editor window. If you suppress the error dialog, errors will still show up here in this log. In addition, compile errors now also go here instead of popping up a dialog. The log's visibility can be toggled from the Script menu.

New error dialog with reduced error info

### CODE REVIEW

**Comment by freezy** [comment]
Looks awesome! 

FYI if you [ignore whitespaces](https://github.com/vpinball/vpinball/pull/19/files?diff=unified&w=1), the diff is "only" +615/-26 lines.

**Comment by jsm174** [comment]
This is very cool! 

BTW, you'll need to add the new files:

```
dialogs\ScriptErrorDialog.cpp
dialogs\ScriptErrorDialog.h
```
 
to

https://github.com/vpinball/vpinball/blob/master/cmake/CMakeLists_win-x64.txt

and

https://github.com/vpinball/vpinball/blob/master/cmake/CMakeLists_win-x86.txt

so the CI (github not appveyor) will compile.

**Comment by CraftedCart** [comment]
Ahh forgot about the CMake scripts ;P

And yeah, not entirely sure what happened to make all the line endings change in the VS project files, my best guess is perhaps because git-for-windows defaults to having autocrlf enabled, and I had to manually merge the project files a little ><  
Sorry about that

**Comment by toxieainc** [comment]
Thanks!

**Comment by jsm174** [comment]
@CraftedCart  - I know this is merged, but we did notice AppVeyor CI is failing. That uses VC 2017. Looks like it can't find `DBGPROP_INFO_FULLNAME` and `DBGPROP_INFO_VALUE`:

```
c:\projects\vpinball-c2whj\codeview.cpp(1122): error C2065: 'DBGPROP_INFO_FULLNAME': undeclared identifier [C:\projects\vpinball-c2whj\VisualPinball.net2017.vcxproj]
c:\projects\vpinball-c2whj\codeview.cpp(1122): error C2065: 'DBGPROP_INFO_VALUE': undeclared identifier [C:\projects\vpinball-c2whj\VisualPinball.net2017.vcxproj]
```

**Comment by CraftedCart** [comment]
Huhh - I'd like to think plopping a `#include <DbgProp.h>` in codeview.cpp should do it?

**Comment by jsm174** [comment]
@CraftedCart - I tried that [here](https://github.com/vpinball/vpinball/commit/cda6cdcb591c2c0ef6fa81fad9e22493d419c61b 
), but it didn't seem to work.

**Comment by CraftedCart** [comment]
Ah, poking around various versions of `DbgProp.h`...

Looks like DbgProp in the 7.1 Windows SDK has `PROP_INFO_FULLNAME` and `PROP_INFO_VALUE`, whereas in the Win10 SDK, it has both those names, as well as `DBGPROP_` prefixed names.

So changing the `DBGPROP_` prefix to simply `PROP_` looks like it should do it.

**Comment by jsm174** [comment]
> So changing the `DBGPROP_` prefix to simply `PROP_` looks like it should hopefully do it.

Awesome. That worked. Thanks!

**Comment by CraftedCart** [comment]
Sweeet!

**Pull request merged**
