### PR TITLE
feat(vbscript): create object error message

### PR DESCRIPTION
**Pull request by francisdb**
To improve debugging scripts on standalone

image

### CODE REVIEW

**Comment by jsm174** [comment]
this is not cross platform. Even if it is working, it shouldn't. 

```
%S (uppercase) is used in Microsoft's C with the Windows API to print wchar_t* (wide characters). This usage is not standard in other C environments, where %S can have different meanings or might not be supported at all.
```

Please just refactor

https://github.com/vpinball/vpinball/blob/9b49a0582b03af8a84e6086cf500d312366acfb2/def.cpp#L655

Look at the `hres` and then `PLOGE` vs `PLOGI`

**Comment by francisdb** [comment]
image

Do you think this should be logged on error?

**Comment by jsm174** [comment]
> Do you think this should be logged on error?

Not sure I follow completely, but we can't really exit immediately here. Returning no object is a valid thing. ie, in windows a user might not have a COM object installed and the table could be smart enough to handle it.

**Comment by jsm174** [comment]
oh warning vs error. sorry, now it makes sense.. warning is fine.

**Pull request merged**
