### PR TITLE
Use RGB16F instead of RGB32F

### PR DESCRIPTION
**Pull request by vbousquet**
This PR proposes to use half float instead of full float for HDR textures, in order to improve performance and allows large use of HDR textures for flashers/primitives. The PR was built and then tested by a few members of the VPW group on different hardwares. No regression was identified while performance benefit was obtained.

Beside the overall performance gain, this PR allows older GPU to be able to play tables with lots of HDR flasher/primitives (GPU llike GTX 650,...) while for the time being they would either overflow due to the memory consumption or slow down due to memory bandwidth.

This is proposed as a direct change (not as an option) since the tests did not show any regression and always benefits. Though, this could be made an option in the video preferences (but it will make them a bit more complex and need a bit more support).

The test were made on the DX9 backend, not the SDL one (I'm not sure of its state at the moment), but I can perform further test if you want.

### CODE REVIEW

**Comment by toxieainc** [comment]
Good idea. I will most likely merge it as-is later-on, and then still make it an option though (and wire it to the respective presets in the video preferences). The reason i picked fp32 is that 'real' HDRs easily feature way too large values for fp16 (=limited by 65504), but i guess that a) everybody just uses what is available on the net for free (i.e. HDRs that are mostly LDRs++) or b) these high peaks are averaged out anyway during mipmap computations (as the highest levels are not picked that often).

**Comment by toxieainc** [comment]
..oh, and having the same for VPVR would be nice, too.

**Comment by vbousquet** [comment]
Ok, nice. I will prepare the PR for VPVR.

**Comment by toxieainc** [comment]
I just commited a variant of your changes that handles larger values automatically. Thanks!

**Comment by toxieainc** [comment]
..oh, and please verify/test my variant again, thanks!

**Pull request closed without merging**
