### PR TITLE
PinSim::FrontEndControls (10.8.0); OpenPinDev fix

### PR DESCRIPTION
**Pull request by mjrgh**
Port of PinSim::FrontEndControls (#1921) to 10.8.0.  Also applies OpenPinDev fix and plunger speed fix for scripted firing.

### CODE REVIEW

**Comment by toxieainc** [comment]
@mjrgh Please resolve the conflicts, then i'll merge, thanks!!

**Comment by jsm174** [comment]
Also, somewhere along the line can we get a fix for these warnings:

```
[ 32%] Building CXX object CMakeFiles/vpinball.dir/third-party/include/imgui/imgui_draw.cpp.o
/Users/runner/work/vpinball/vpinball/third-party/include/hid-report-parser/hid_report_parser.cpp:227:13: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
                                if (res = AssertMinMaxItemsAreMatched())
                                    ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/vpinball/vpinball/third-party/include/hid-report-parser/hid_report_parser.cpp:227:13: note: place parentheses around the assignment to silence this warning
                                if (res = AssertMinMaxItemsAreMatched())
                                        ^
                                    (                                  )
/Users/runner/work/vpinball/vpinball/third-party/include/hid-report-parser/hid_report_parser.cpp:227:13: note: use '==' to turn this assignment into an equality comparison
                                if (res = AssertMinMaxItemsAreMatched())
                                        ^
                                        ==
/Users/runner/work/vpinball/vpinball/third-party/include/hid-report-parser/hid_report_parser.cpp:229:13: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
                                if (res = ParseMainItems(item, p, data_size, handler))
                                    ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/vpinball/vpinball/third-party/include/hid-report-parser/hid_report_parser.cpp:229:13: note: place parentheses around the assignment to silence this warning
                                if (res = ParseMainItems(item, p, data_size, handler))
                                        ^
                                    (                                                )
/Users/runner/work/vpinball/vpinball/third-party/include/hid-report-parser/hid_report_parser.cpp:229:13: note: use '==' to turn this assignment into an equality comparison
                                if (res = ParseMainItems(item, p, data_size, handler))
                                        ^
                                        ==
/Users/runner/work/vpinball/vpinball/third-party/include/hid-report-parser/hid_report_parser.cpp:235:13: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
                                if (res = ParseGlobalItems(item, p, data_size))
                                    ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/vpinball/vpinball/third-party/include/hid-report-parser/hid_report_parser.cpp:235:13: note: place parentheses around the assignment to silence this warning
                                if (res = ParseGlobalItems(item, p, data_size))
                                        ^
                                    (                                         )
/Users/runner/work/vpinball/vpinball/third-party/include/hid-report-parser/hid_report_parser.cpp:235:13: note: use '==' to turn this assignment into an equality comparison
                                if (res = ParseGlobalItems(item, p, data_size))
                                        ^
                                        ==
/Users/runner/work/vpinball/vpinball/third-party/include/hid-report-parser/hid_report_parser.cpp:240:13: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
                                if (res = ParseLocalItems(item, p, data_size))
                                    ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/vpinball/vpinball/third-party/include/hid-report-parser/hid_report_parser.cpp:240:13: note: place parentheses around the assignment to silence this warning
                                if (res = ParseLocalItems(item, p, data_size))
                                        ^
                                    (                                        )
/Users/runner/work/vpinball/vpinball/third-party/include/hid-report-parser/hid_report_parser.cpp:240:13: note: use '==' to turn this assignment into an equality comparison
                                if (res = ParseLocalItems(item, p, data_size))
                                        ^
                                        ==
/Users/runner/work/vpinball/vpinball/third-party/include/hid-report-parser/hid_report_parser.cpp:253:11: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
                if (res = AssertMinMaxItemsAreMatched())
                    ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/vpinball/vpinball/third-party/include/hid-report-parser/hid_report_parser.cpp:253:11: note: place parentheses around the assignment to silence this warning
                if (res = AssertMinMaxItemsAreMatched())
                        ^
                    (                                  )
/Users/runner/work/vpinball/vpinball/third-party/include/hid-report-parser/hid_report_parser.cpp:253:11: note: use '==' to turn this assignment into an equality comparison
                if (res = AssertMinMaxItemsAreMatched())
                        ^
                        ==
5 warnings generated.
[ 33%] Building CXX object CMakeFiles/vpinball.dir/third-party/include/imgui/imgui_impl_sdl3.cpp.o
[ 33%] Building CXX object CMakeFiles/vpinball.dir/third-party/include/im
```

**Comment by jsm174** [comment]
Also I think I have the standalone branch rebased properly. I'm seeing multiple copies of `OpenPinballDeviceReport struct`, one in `pininput.h` and on in `pininput_OpenPinDev.cpp`? Is that correct?

**Comment by mjrgh** [comment]
@toxieainc - I'll take a look at the merge conflicts.

@jsm174 - I think I already fixed all of those warnings in hid_report_parser.cpp the 8.1 branch, and I thought I carried the latest there over here, so I'm not sure why you're seeing those; maybe a rebase/merge problem, or maybe I just grabbed an older copy somehow.  I'll take a look.  (img_gui isn't anything I added.)  The two copies of the struct are probably also a merge error.

**Comment by jsm174** [comment]
sorry, I copied and pasted too much from the build. the imgui stuff is unrelated. I'll fix the comment

**Comment by mjrgh** [comment]
Okay, fixed the merge conflicts.  Still not sure what happened to my warning fixes in hid_report_parser.cpp - looks like they're still in the latest 10.8.1 branch too. I thought I fixed those in 10.8.1 some time ago, but I must have done that on a branch that didn't get checked in or something.

**Comment by mjrgh** [comment]
Added fixes for the warnings.

**Comment by toxieainc** [comment]
Thanks!

**Pull request merged**
