### PR TITLE
Window POV fixes (and other fixes)

### PR DESCRIPTION
**Pull request by vbousquet**
This https://github.com/vpinball/vpinball/issues/827 report allowed me to finally identify what felt wrong with the window POV:
Problem 1 : virtual vs real world sizes:
- Screen size and Player position are real world units
- Playfield size and Bottom/Top Z offsets are virtual world units (as well as other offsets which are directly applied to the playfield bounds)
- The matching between the 2 depends on physical size of screen
- Physical sizes must be scaled to virtual world
	
Problem 2 : window mode is performing double axis fitting:
- Fitting is done on the X and the Y axis (most constraining of the both), then applying aspect ratio, so the result is not entirely stable and makes other part of the algorithm (that expects a single fitting axis) wrong

Problem 3 : in the current implementation, inclination does not take in account y offsets, nor the scaling (which has an impact is y and z scaling are not equals) which is a bug

Problem 4 : position of "zero point depth":
- The table author does not know anything about the user setting. He should only define the glass position => use table glass top/bottom.
- The player may choose to place its screen rendering at any position relatively to the real playfield/glass volume (defined by the table author)
 
These commits fixes all this by:
- Fix inclination computation
- Only fit on the y axis => perform fitting on the center playfield axis
- Remove x wnd offsets => only use x offset and x scaling, in the end, it gives the same possibilities
- Remove y wnd offsets => only use y offset and y scaling, in the end, it gives the same possibilities
- Add top/bottom glass height to the table properties (not POV)
  - Rename existing glass height as top glass height
  - Add bottom glass height, initialized with the existing glass height for existing table
  - Adjust physics, input and UI accordingly
  - Add ui for it (using cm)
- Create a display physical size setting in video setting
- Compute real to virtual world scale (defaults to 1) and apply it to player position
- Adjust UI in order to have real world sizing when scale is at 100% (allow to easily check if everything is set up correctly)

This PR also contains other miscallenous fixes (most noticeable is the long time standing blurry playfield as reported here: https://github.com/vpinball/vpinball/issues/817, the other big one being a fix to ball reflection brightness)

### CODE REVIEW

**Comment by SmedleyB** [comment]
@vbousquet First impression of this change is amazing. I reset the Windowed POV and the default it creates looks almost exactly like what I had dialed in myself in previous versions. Player X/Y/Z react like I would expect and I appreciate how the default view is placed - how the apron is cut off and the top of the table. Looking forward to getting a 21:9 monitor installed and trying this new feature on it as well. Looks like it will work great.

**Comment by studlygoorite** [comment]
Question about the Dimensions Manager, if I load a table, say Bad Cats and go to the dimension manager and double click and apply the William standard size, I see it will then automagically create the POV for me. Is this correct, because it's damn close to perfect but part of my apron is cut off and I'm thinking that the measurement for my cabinet playfield that I entered into the VPX Graphics Options may not be exact and causing this cut off, then 1 cm-ish might make the difference? Also tried Cactus Canyon and it was a little too vertically stretched but it was a quick and easy fix. Is the plan to use this Dimension Manager now, or in the future, to create the POVs for us?

**Comment by vbousquet** [comment]
@studlygoorite The dimension manager has nothing to do with the POV. It's just a helper when creating a table to start with the right dimensions (need to fix though, had a look and the guns'n roses size is wrong).

**Comment by SmedleyB** [comment]
@vbousquet The latest version of Cue Ball Wizard is a good one to check out (https://vpuniverse.com/files/file/15354-cue-ball-wizard-gottlieb-1992-mikcab_mod/).
The generated default POV has a lot of black space at the top of the screen - I assume there is some setting or some object on that table that it is accounting for when building the POV. But it was still a good start to the POV and easy to fix with a couple quick changes.

**Comment by DanLShane** [comment]
Well, the new POV has thrown off my red/cyan anaglyph view.  The new FATHOM playfield looks not horrible, but the convergence is way, way off -- a lot farther than before. It's especially noticeable on the apron cards.
PXL_20230928_155925425

**Pull request merged**
